/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CheckoutForm: typeof import('./src/components/CheckoutForm.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    PlanCard: typeof import('./src/components/PlanCard.vue')['default']
    PlanView: typeof import('./src/components/PlanView.vue')['default']
    Posts: typeof import('./src/components/Posts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
